
services:
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    restart: always
    ports:
      - "25500:25500"
    volumes:
      - ./fduzs_config.ini:/base/config/fduzs_config.ini

  sub-web:
    image: ghcr.io/souleastforest/sub-web:latest
    container_name: sub-web
    restart: always
    ports:
      - "25501:80"
